### ISSUE TITLE
master branch is out of sync

### ISSUE THREAD

**Issue by talhaHavadar** [Xilinx/kria-base-firmware#2]
xlnx_rel_v2023.1 branch is a head of master branch can we sync them?

**Comment by talhaHavadar** [comment]
I also see that v2023.1 is not tagged. Can we maybe tag the latest version using semantic versioning like v1.0 etc?

**Comment by chkohn** [comment]
I updated master, it is in sync now

**Comment by chkohn** [comment]
what commit are you currently packaging? is it https://github.com/Xilinx/kria-base-firmware/commit/d512881ad56fcb8ad3bffea543280c5b357bb9ea? please let me know.

And yes, we should reset the versioning and start with 1.0.

**Comment by chkohn** [comment]
@talhaHavadar this commit https://github.com/Xilinx/kria-base-firmware/commit/b7ad360cd5d2483155a69263b170fb1329023b5d is what you would like to tag as 1.0 I assume.

**Comment by talhaHavadar** [comment]
Yes that would be great!

**Comment by chkohn** [comment]
@talhaHavadar here is the tag as discussed:
https://github.com/Xilinx/kria-base-firmware/releases/tag/v1.0
