### ISSUE TITLE
What does k24_starter_kits.bit enable PL's function?

### ISSUE THREAD

**Issue by pojiro** [Xilinx/kria-base-firmware#5]
Hi, I'd like to know the function which are enabled by k24_starter_kits.bit. I couldn't find the any information yet.
If you have any infomation about it, please let me know. 

Thank you

**Comment by chkohn** [comment]
@pojiro 

@sweatharao can chime in but as far as I know, it's only the two pins that connect to the fan. note: by default there is no fan installed at least on the kd240 starter kit.

application-specific prebuilt bitstreams can be found in this repo: https://github.com/Xilinx/kria-apps-firmware. check https://xilinx.github.io/kria-apps-docs/kd240/build/html/index.html for documentation.

**Comment by pojiro** [comment]
@chkohn Thanks for your quick reply!

I could confirm that the two pins voltage are changed by the k24_starter_kits.bit. 

- Before load: 12V
- After load: 0V

And I also found the fan pin GND, J13 GND, is connected to `HDA08_CC` on PL in the KD240's schematic.
That is written in the following document too, 

https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/1641152513/Kria+SOMs+Starter+Kits#Fan-Control

Thank you!
